# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('target', models.TextField()),
                ('short_url', models.TextField()),
                ('token', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateField()),
            ],
        ),
    ]
